blank_issues_enabled: false
contact_links:
  - name: ğŸ“š ë¬¸ì„œ
    url: https://github.com/modern-agile-team/quiz-game-io-front/docs
    about: í”„ë¡œì íŠ¸ ë¬¸ì„œë¥¼ í™•ì¸í•˜ì„¸ìš”
  - name: ğŸ’¬ ì§ˆë¬¸
    url: https://github.com/modern-agile-team/quiz-game-io-front/discussions
    about: ì§ˆë¬¸ì€ Discussionì„ ì´ìš©í•´ì£¼ì„¸ìš”
